name: built_value_generator
version: 7.1.0
description: >
  Value types with builders, Dart classes as enums, and serialization.
  This library is the dev dependency.
homepage: https://github.com/google/built_value.dart

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  # This range allows consumption by packages that need more recent build_*
  # versions without also requiring a newer Dart SDK version. The range is also
  # safe, as code in this package analyzes cleanly and passes tests on both
  # major versions of the analyzer.
  analyzer: '>=0.39.3 <0.41.0'
  build: ^1.0.0
  build_config: '>=0.3.1 <0.5.0'
  built_collection: '>=2.0.0 <5.0.0'
  built_value: '>=7.0.0 <7.2.0'
  source_gen: ^0.9.0
  quiver: '>=0.21.0 <3.0.0'

dev_dependencies:
  build_test: ^0.10.3
  # This range works around the InconsistentAnalysisException issue when
  # building this package on newer versions of Dart, while still remaining
  # compatible with the above analyzer range.
  # See https://github.com/google/built_value.dart/issues/941#issuecomment-737884696
  build_runner: '>=1.0.0 <=1.10.2'
  logging: ^0.11.0
  pedantic: ^1.4.0
  test: ^1.0.0
